
window.TEAM_IROBOT_PRODUCTS = [
  {
    id:"mini-autoempty",
    name:"Roomba Mini + AutoEmpty",
    short:"Roomba Mini",
    family:"Mini",
    year:2026,
    image:"https://www.irobot-jp.com/product/img/family/260219/roomba-min-ae_wh.png",
    tags:["compact","combo","autoempty"],
    summary:"日本の住環境を意識した小型モデル。掃除機がけに加え、使い捨て床拭きシートで水拭きにも対応。",
    suction:"—",
    mop:"シート式",
    dock:"AutoEmpty",
    navigation:"ClearView LiDAR",
    obstacle:"物体検知",
    bestFor:"省スペース・小さな間取り",
    official:"https://www.irobot-jp.com/product/"
  },
  {
    id:"mini-slim",
    name:"Roomba Mini Slim",
    short:"Mini Slim",
    family:"Mini",
    year:2026,
    image:"https://www.irobot-jp.com/product/img/family/260219/roomba-min-sc_wh.png",
    tags:["compact","combo"],
    summary:"縦置きできるSlimCharge充電スタンドを採用した省スペースモデル。",
    suction:"—",
    mop:"シート式",
    dock:"SlimCharge",
    navigation:"ClearView LiDAR",
    obstacle:"物体検知",
    bestFor:"置き場所をできるだけ小さくしたい",
    official:"https://www.irobot-jp.com/product/"
  },
  {
    id:"105-combo-ae",
    name:"Roomba 105 Combo + AutoEmpty",
    short:"105 Combo",
    family:"105",
    year:2025,
    image:"https://store.irobot-jp.com/client_info/FS/itemimage/Y351060.jpg",
    tags:["combo","autoempty"],
    summary:"掃除機がけと水拭きをシンプルにまとめたエントリー寄りのComboモデル。",
    suction:"—",
    mop:"マイクロファイバー",
    dock:"AutoEmpty",
    navigation:"ClearView LiDAR",
    obstacle:"物体検知",
    bestFor:"初めてのロボット掃除機",
    official:"https://store.irobot-jp.com/item/Y351060.html"
  },
  {
    id:"plus-405",
    name:"Roomba Plus 405 Combo",
    short:"Plus 405",
    family:"Plus",
    year:2025,
    image:"https://www.irobot-jp.com/product/img/family/260219/roomba-plus-405-image.png",
    tags:["combo","autowash","autoempty"],
    summary:"回転モップとAutoWash充電ステーションで、水拭き後のメンテナンスまで自動化。",
    suction:"—",
    mop:"DualClean回転モップ",
    dock:"AutoWash",
    navigation:"ClearView LiDAR",
    obstacle:"物体検知",
    bestFor:"水拭きの手間を減らしたい",
    official:"https://store.irobot-jp.com/item/G185060.html"
  },
  {
    id:"plus-515",
    name:"Roomba Plus 515 Combo",
    short:"Plus 515",
    family:"Plus",
    year:2026,
    image:"https://www.irobot-jp.com/product/img/family/260804/roomba-plus-515-image_pc.png?1234=",
    tags:["compact","combo","autowash","autoempty"],
    summary:"日本の住環境を意識したコンパクトなPlusモデル。モップ洗浄・乾燥まで自動化。",
    suction:"—",
    mop:"DualClean回転モップ",
    dock:"AutoWash",
    navigation:"ClearView LiDAR",
    obstacle:"物体検知",
    bestFor:"コンパクトさと自動メンテナンス",
    official:"https://store.irobot-jp.com/category/ROOMBA/N285060.html"
  },
  {
    id:"plus-615",
    name:"Roomba Plus 615 Combo",
    short:"Plus 615",
    family:"Plus",
    year:2026,
    image:"https://www.irobot.co.uk/dw/image/v2/BFXP_PRD/on/demandware.static/-/Library-Sites-iRobotSharedLibrary/default/dw466c504b/EMEA/2026/615/Roomba_Plus_615_Combo_WashOnly_Black_Photo_In-situ_PowerSpinRollerMop_DTC_3000x3000.jpg?fmt=auto&sw=1000",
    tags:["combo","autowash"],
    summary:"2段階水拭き、PowerSpinローラーモップ、最大30,000Pa吸引を組み合わせた2026年の高機能Plusモデル。",
    suction:"最大30,000Pa",
    mop:"PowerSpinローラーモップ / SprayForce AI",
    dock:"Wash Only Dock",
    navigation:"ClearView Pro LiDAR",
    obstacle:"PrecisionVision AI",
    bestFor:"水拭き性能・障害物回避を重視",
    official:"https://store.shopping.yahoo.co.jp/irobotstore-jp/v184060.html"
  },
  {
    id:"max-775",
    name:"Roomba Max 775 Combo",
    short:"Max 775",
    family:"Max",
    year:2026,
    image:"https://www.irobot-jp.com/product/img/family/260717/roomba-max-775-aw-image.png",
    tags:["combo","autowash","autoempty"],
    summary:"Maxシリーズの上位Combo。伸縮モップとAI障害物回避、AutoWashを組み合わせる。",
    suction:"105 Combo比 約4倍",
    mop:"PowerSpinローラーモップ",
    dock:"AutoWash",
    navigation:"ClearView Pro LiDAR",
    obstacle:"PrecisionVision AI",
    bestFor:"清掃力・自動化を最優先",
    official:"https://store.irobot-jp.com/item/X285060.html"
  },
  {
    id:"max-715",
    name:"Roomba Max 715 Vac",
    short:"Max 715",
    family:"Max",
    year:2026,
    image:"https://www.irobot-jp.com/product/img/family/260717/roomba-max-715-ae-image.png",
    tags:["vac","autoempty"],
    summary:"水拭きを省き、掃除機がけに集中したMaxシリーズ。",
    suction:"105 Combo比 約4倍",
    mop:"なし",
    dock:"AutoEmpty",
    navigation:"ClearView Pro LiDAR",
    obstacle:"物体検知",
    bestFor:"掃除機がけ特化・カーペット中心",
    official:"https://www.irobot-jp.com/product/"
  }
];
